### ISSUE TITLE
BUGS-8/15 7:10 am version of Master throwing 2 geolocation.js errors

### ISSUE THREAD

**Issue by gnkatchmar** [gnkatchmar/Breakfast-Club#69] opened 2016-08-15 14:15 UTC
Line 44 can't find "entryform" ID (went through some earlier branches and could not find where this should be)
Line 310 markerarray not defined

**Comment by djado** [comment] 2016-08-15 18:18
Line 44 is due to some naming having changed in Index.html
Line 310 is very strange. The edits that I made to Index.html for my code to work weren't merged for some reason. I remember looking at them in the pull request even. Now when I look at the proposed pull request, it seems they aren't there.

Easy fixes, but I wish I knew why that happened.

**Comment by gnkatchmar** [comment] 2016-08-15 18:22
May have happened in the conflict merge I did. I went with the "chunk" that had the correct values for the dropdown which were accomplished in yesterday's "Aug14..." pull request thinking that was the "right" one.

**Comment by djado** [comment] 2016-08-15 18:22
Here is the cause of the 310 error. First the code that was supposed to be in the pull request:

```
      <form name="nhoodselect" onsubmit = "test(nh1, nh2, nh3); return false" action="index.html">
        <input type="checkbox" name="nh1" value="SEPDX" data-quad="SE">SE Portland<br>
        <input type="checkbox" name="nh2" value="NEPDX" data-quad="NE">NE Portland<br>
        <input type="checkbox" name="nh3" value="DTPDX" data-quad="SW">Downtown Portland<br>
        <input type="submit" value="Submit Search">
      </form>
```

And now the code as it is this morning. Notice the missing 'data-quad's:

```
                    <form name="nhoodselect" onsubmit = "test(nh1, nh2, nh3); return false">
                    <input type="checkbox" name="nh1" value="SEPDX" checked>SE Portland<br>
                    <input type="checkbox" name="nh2" value="NEPDX" checked>NE Portland<br>
                    <input type="checkbox" name="nh3" value="DTPDX" checked>Downtown Portland<br>
                    <input type="submit" value="Submit Search">
                    </form>
```

**Comment by djado** [comment] 2016-08-15 18:24
Ah ok. As long as we can explain it, it's an easy fix.

**Comment by gnkatchmar** [comment] 2016-08-15 19:32
I'm holding off on substantive changes until this is resolved and pushed to master. Still need to complete local storage of form inputs (have to add id's to the checkbox form in question).

**Comment by djado** [comment] 2016-08-15 20:00
I've submitted a PR with the fix.

**Comment by djado** [comment] 2016-08-15 20:10
This bug is fixed. However due to page styling, the launchpage (even though invisible) is blocking access to the form elements. You can see this by setting #launchpage to display:none

Creating new issue for this bug

**Closed as completed** 2016-08-15 20:16 UTC
Labels: bug
